name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


permissions:
  contents: write  

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies (Linux and macOS)
        if: runner.os != 'Windows'
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Build executable (not windows)
        if: runner.os != 'Windows'
        run: |
          pyinstaller --onefile --windowed \
          --icon=assets/tetris_icon.icns \
          --add-data "assets:assets" \
          main.py
        env:
          VERSION: ${{ github.sha }}
            
      - name: Build executable (windows)
        if: runner.os == 'Windows'
        run: |
          & pyinstaller --onefile --windowed `
            --icon=assets/tetris_icon.ico `
            --add-data "assets;assets" `
            main.py
        env:
          VERSION: ${{ github.sha }}

      - name: Rename executable (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: mv dist/main dist/Tetris-B-Linux
      - name: Rename executable (macOS)
        if: matrix.os == 'macos-latest'
        run: mv dist/main dist/Tetris-B-macos
      - name: Rename executable (Windows)
        if: matrix.os == 'windows-latest'
        run: mv dist/main.exe dist/Tetris-B-windows.exe

      - name: Upload artifact for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Tetris-B-Linux
          path: dist/Tetris-B-Linux
      - name: Upload artifact for macOS
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Tetris-B-macos
          path: dist/Tetris-B-macos
      - name: Upload artifact for Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Tetris-B-windows
          path: dist/Tetris-B-windows.exe

  cd:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact for Ubuntu
        uses: actions/download-artifact@v2
        with:
          name: Tetris-B-Linux
          path: ./dist/
      - name: Download artifact for macOS
        uses: actions/download-artifact@v2
        with:
          name: Tetris-B-macos
          path: ./dist/
      - name: Download artifact for Windows
        uses: actions/download-artifact@v2
        with:
          name: Tetris-B-windows
          path: ./dist/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset for Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/Tetris-B-Linux
          asset_name: Tetris-B-Linux
          asset_content_type: application/octet-stream

      - name: Upload Release Asset for macOS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/Tetris-B-macos
          asset_name: Tetris-B-macos
          asset_content_type: application/octet-stream

      - name: Upload Release Asset for Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/Tetris-B-windows.exe
          asset_name: Tetris-B-windows.exe
          asset_content_type: application/octet-stream
